on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp:latest
    steps:
    - uses: actions/checkout@v2
    - run: make build

  test:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    needs: [build]
    services:
    image: postgres
    env:
    - POSTGRES_USER: phabrpguser
    - POSTGRES_PASSWORD: pgpwd4habr
    - POSTGRES_BD: testdocker
    ports:
    - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - run: make build && make test  

  coverage:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - run: make build && make coverage
