on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp:latest
    services: postgres:latest
    steps:
    - uses: actions/checkout@v2
    - run: make build

  test:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    services: postgres:latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - run: make build && make test  

  coverage:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    services: postgres:latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - run: make build && make coverage
