on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp:latest
    steps:
    - uses: actions/checkout@v3
    - run: make build

  test:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    needs: [build] 

    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        networks: db_network

    steps:
    - uses: actions/checkout@v3
    - run: docker network create db_network
    - run: docker network inspect db_network
    - run: make build && make test  

  coverage:
    runs-on: ubuntu-latest
    container: dnonakolesax/dbcpp
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - run: make build && make coverage
